---
title: East Coast Kelly
tagline: Simple Living
description: Teaching busy mothers how to live simplify and transform their days from
  chaos to calm
url: https://flamboyant-mccarthy-691f26.netlify.com/
baseurl: ''
author:
  name: Kelly Briggs
  url: ''
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-menus
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#2C1C0D"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
markdown: kramdown
highlighter: rouge
facebook: 'http://www.facebook.com/kelly.briggs'
twitter: ''
instagram: 'http://www.instagram.com/eastcoastkelly'