---
title: East Coast Kelly
tagline: Simple Living
description: The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme
  for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.
url: https://flamboyant-mccarthy-691f26.netlify.com/
baseurl: ''
author:
  name: Andrew Fong
  url: https://twitter.com/fongandrewc
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-menus
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
markdown: kramdown
highlighter: rouge
